### ISSUE TITLE
NPE HttpThread.processRequest(HttpThread.java:107)

### ISSUE THREAD

**Issue by ghollf** [woheller69/TimeLapseCamera#52]
FATAL EXCEPTION: Thread-50
Process: org.woheller69.TimeLapseCam, PID: 25327
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference
at at.andreasrohner.spartantimelapserec.rest.HttpThread.processRequest(HttpThread.java:107)
at at.andreasrohner.spartantimelapserec.rest.HttpThread.run(HttpThread.java:90)

**Comment by ghollf** [comment]
So readLine in HttpThread.java:106 "sometimes" returns a null pointer

**Comment by ghollf** [comment]
```
1718185297.551 10103 25327 25367 I TcpListener: New connection from /192.168.178.38:58961
1718185297.554 10103 25327 25367 D RestService: Cleaning up finished session...
1718185297.554 10103 25327 25367 D RestService: Thread joined
1718185297.554 10103 25327 25367 D RestService: Cleaning up finished session...
1718185297.555 10103 25327 25367 D RestService: Thread joined
1718185297.555 10103 25327 25367 D RestService: Cleaning up finished session...
1718185297.568 10103 25327 25367 D RestService: Thread joined
1718185297.569 10103 25327 25367 D RestService: Registered session thread
1718185297.575 10103 25327 25367 I TcpListener: New connection from /192.168.178.38:58966
1718185297.577 10103 25327 25367 D RestService: Registered session thread
1718185297.594 10103 25327 28061 D HttpThread: Request: «GET» «/1/device/battery» « HTTP/1.1»
1718185297.598 10103 25327 25367 I TcpListener: New connection from /192.168.178.38:58962
1718185297.600 10103 25327 25367 D RestService: Registered session thread
1718185297.603 10103 25327 28062 D HttpThread: Request: «GET» «/1/ctrl/status» « HTTP/1.1»
1718185297.606 10103 25327 25367 I TcpListener: New connection from /192.168.178.38:58963
1718185297.630 10103 25327 25367 D RestService: Cleaning up finished session...
1718185297.630 10103 25327 25367 D RestService: Thread joined
1718185297.630 10103 25327 25367 D RestService: Registered session thread
1718185297.631 10103 25327 25367 I TcpListener: New connection from /192.168.178.38:58964
1718185297.632 10103 25327 25367 D RestService: Cleaning up finished session...
1718185297.632 10103 25327 25367 D RestService: Thread joined
1718185297.632 10103 25327 25367 D RestService: Registered session thread
1718185297.637 10103 25327 25367 I TcpListener: New connection from /192.168.178.38:58965
1718185297.637 10103 25327 25367 D RestService: Registered session thread
1718185297.638 10103 25327 28064 D HttpThread: Request: «GET» «/1/ctrl/param» « HTTP/1.1»
1718185297.640 10103 25327 28065 D HttpThread: Request: «GET» «/1/current/lastimg» « HTTP/1.1»
1718185297.641 10103 25327 28066 D HttpThread: Request: «GET» «/1/current/imgcount» « HTTP/1.1»
1718185321.997  wifi   839   839 I wpa_supplicant: wlan0: WPA: Group rekeying completed with 44:4e:6d:82:88:0e [GTK=CCMP]
1718185366.869 10103 25327 28063 E AndroidRuntime: FATAL EXCEPTION: Thread-50
1718185366.869 10103 25327 28063 E AndroidRuntime: Process: org.woheller69.TimeLapseCam, PID: 25327
1718185366.869 10103 25327 28063 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference
1718185366.869 10103 25327 28063 E AndroidRuntime: 	at at.andreasrohner.spartantimelapserec.rest.HttpThread.processRequest(HttpThread.java:107)
1718185366.869 10103 25327 28063 E AndroidRuntime: 	at at.andreasrohner.spartantimelapserec.rest.HttpThread.run(HttpThread.java:90)
1718185366.893 10103 25327 28063 I Process : Sending signal. PID: 25327 SIG: 9
1718185366.914 media   244   244 I CameraSource: Camera recording proxy died
1718185366.914 media   244   244 D MPEG4Writer: Video track stopping
1718185366.914 media   244   244 D MPEG4Writer: Video track source stopping
1718185366.915 media   244 26390 I MediaCodecSource: encoder (video) stopping
1718185366.916 media   244   939 E mm-libcamera2: PROFILE HAL: stopPreview(): E: 1718185366.916531470
1718185366.917  1000   616  1626 I ActivityManager: Process org.woheller69.TimeLapseCam (pid 25327) has died
1718185366.917  1000   616  1626 D ActivityManager: cleanUpApplicationRecord -- 25327
1718185366.917  1000   616  1626 W ActivityManager: Scheduling restart of crashed service org.woheller69.TimeLapseCam/at.andreasrohner.spartantimelapserec.ForegroundService in 1000ms
1718185366.917  1000   616  1626 W ActivityManager: Service crashed 2 times, stopping: ServiceRecord{42d7060 u0 org.woheller69.TimeLapseCam/at.andreasrohner.spartantimelapserec.rest.RestService}
```

**Comment by woheller69** [comment]
is there a way to reproduce the error?

**Comment by ghollf** [comment]
Irgendwie ist die Webserverimplementierung "halbgar". APP hab ich gestern und heute über das Webinterface betrieben mit immer mal wieder restart der Aufzeichnung (mp4) und parallelem Download des letzten aufgenommenen Files über listhtml und ist dabei nach 1-2h immer abgeraucht. Im obigen Log schaut es ja so aus, dass er sich bei den 3 parallelen Requests aus der Weboberfläche verzettelt. Auf jeden Fall sollte null aus dem readLine zu keinem NPE mehr führen - sondern nur zu einem Logeintrag. 

Somehow the web server implementation is "half-baked". I ran the APP yesterday and today via the web interface with repeated restarts of the recording (mp4) and parallel download of the last recorded file via listhtml and it always crashed after 1-2 hours. In the log above it looks like it gets bogged down with the 3 parallel requests from the web interface. In any case, null from the readLine should no longer lead to an NPE - but only to a log entry. 

Translated with DeepL.com (free version)

**Comment by woheller69** [comment]
@andreasb242 can you have a look at this?

**Comment by andreasb242** [comment]
Ja, schaue ich mir an.
>dass er sich bei den 3 parallelen Requests aus der Weboberfläche verzettelt.

3 Downloads von Videos nehme ich an, denn ansonsten ist das ja nicht so einfach zu produzieren?
Ich versuche das zu reproduzieren.
------------

I'll have a look at this.

**Comment by andreasb242** [comment]
@woheller69  Thanks for fixing it! I'm currently not that much developing, because of the summer weather.

**Comment by woheller69** [comment]
I did it because of the summer weather. It is too hot ...
